---
title: "BMI 715 Lab 1"
---

Below are instructions for completing the first lab. If you finish all of the github exercises please feel free to start on the first problem set. After the brief lecture the TAs will be walking around the room to help with both the lab and the problem set. The slides included in this lab show instructions for how to complete the lab using the github GUI. 

## Cloning

Clone the remote repository whose location is specified below to your local machine. 

```
git clone https://github.com/jacobluber/BMI715-Lab-1.git
```

## Creating a branch
Since we are all working in this repo together, you should create a branch to store the changes you are making to whichever files we are tracking with version control. Name your branch with your name.
```
git checkout -b [name_of_your_new_branch]
git push origin [name_of_your_new_branch]
git push --set-upstream origin jacob_luber
```
This code creates a new branch and then subsequently updates the remote repo. 

After everyone else had made branches, you can see their branches:

```
git pull
git branch
```

## Changing Files

Edit this R markdown file "lab1.Rmd" so that you have added your name to the "I Completed This Lab" section at the end of the .Rmd file.


## Adding Files To Be Pushed

You can add files to be pushed remotely by either using:

```git add [FILENAME]```

or add all files:

```git add -A```

Add "lab1.Rmd" so that it will be pushed to the remote repo.

## Commiting

It is important to leave commit messages so that other people you are collaborating with can see what changes you contribuetd to any version code. Please leave a commit message with whatever changes you made.
```git commit -m "You commit message here"```

## Pushing
After you commit changes, you need to push them to the remote repo. Make sure that you are on the branch that you created and not the master branch when you do this. 

```git push```

## Tagging

You can add tags to track software versions. The syntax is shown below as an example. Don't worry about adding a tag now. 
```git tag -a v1.0 -m "version 1.0"```
```git push origin --tags```

## Checking Out A Branch 

You can switch from your branch to the master branch (shared code that everyone is contributing to):
```git checkout master```
Switch to the master branch then switch back to your branch.


## Fixing Merge Conflicts 
We are now going to merge our updates into the shared master branch. 
```
git checkout master
git pull origin master
git merge [name_of_your_new_branch]
git push origin master
```
If there is a merge conflict (somebody else updated master and your changes were to the same areas of a file) this will fail. If this occured and you received a merge conflict error open the "lab1.Rmd" file while still in the master branch. 

You will see something that looks like the below text at one or more points in the text file:
```
[Text]
<<<<<<< HEAD
[Text]
=======
[Text]
>>>>>>> [name_of_your_new_branch]
```

Anything below "<<<<<<< HEAD" but above "=======" are changes made to the master branch. Anything below "=======" but above ">>>>>>> [name_of_your_new_branch]" are changes made to your branch that conflict with the changes to master branch. Delete the lines "=======","<<<<<<< HEAD", and ">>>>>>> [name_of_your_new_branch]" to add both changes, commit the file, then push. Go to github.com to verify that this worked and your name is displaying in the .Rmd file on the master branch. If not, try again! 

## I Completed This Lab
Jacob Luber





